#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

if [ ${OPENSHIFT_NODEJS_IP} ]; then
    REDISIP=${OPENSHIFT_NODEJS_IP}
fi

if [ ${OPENSHIFT_PYTHON_IP} ]; then
    REDISIP=${OPENSHIFT_PYTHON_IP}
fi

if [ ${OPENSHIFT_INTERNAL_IP} ]; then
    REDISIP=${OPENSHIFT_INTERNAL_IP}
fi

if [ ${OPENSHIFT_PHP_IP} ]; then
    REDISIP=${OPENSHIFT_PHP_IP}
fi

REDISPORT=16000
EXEC=${OPENSHIFT_REPO_DIR}bin/redis-server
CLIEXEC=${OPENSHIFT_REPO_DIR}bin/redis-cli

PIDFILE=${OPENSHIFT_DATA_DIR}redis/data/redis.pid
CONF=${OPENSHIFT_DATA_DIR}redis/redis.conf

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -h $REDISIP -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac